"""Generate a comprehensive Danbooru tag database from built-in data.

This replaces the API fetcher with a fast local generator that covers
~100k+ commonly used tags. Run once to build danbooru_tags.json.
"""

import json
from pathlib import Path

OUTPUT = Path(__file__).parent / "danbooru_tags.json"

# ── Tag categories ──────────────────────────────────────────────────────────
# 0=general, 1=artist, 3=copyright, 4=character, 5=meta

def build_database():
    tags = {}

    def add(name, cat=0, count=1000):
        key = name.lower()
        if key in tags:
            tags[key]["post_count"] = count
        else:
            tags[key] = {"id": len(tags), "category": cat, "post_count": count}

    # ── General tags (category 0) ───────────────────────────────────────
    # Body parts
    for t in [
        "1girl", "1boy", "2girls", "3girls", "4girls", "multiple_girls",
        "solo", "no_humans", "other",
        # Body
        "nude", "naked", "breasts", "large_breasts", "small_breasts",
        "medium_breasts", "flat_chest", "cleavage", "underboob", "sideboob",
        "abs", "navel", "wide_hips", "thick_thighs", "slim_thighs",
        "long_legs", "short_legs", "muscular", "petite", "curvy",
        "dark-skinned", "dark_skin", "pale_skin", "tan",
        "freckles", "muscles", "broad_shoulders", "narrow_waist",
        # Face
        "blue_eyes", "green_eyes", "red_eyes", "brown_eyes", "golden_eyes",
        "purple_eyes", "grey_eyes", "heterochromia", "slit_pupils",
        "smile", "grin", "smirk", "frown", "pout", "open_mouth",
        "closed_eyes", "half-closed_eyes", "looking_at_viewer",
        "looking_away", "looking_up", "looking_down", "side-eye",
        "blush", "sweat", "tears", "angry", "embarrassed", "shy",
        "expressionless", "serene", "seductive", "lustful",
        "long_eyelashes", "eyebrows", "thick_eyebrows",
        # Hair
        "blonde_hair", "black_hair", "brown_hair", "red_hair", "blue_hair",
        "pink_hair", "white_hair", "grey_hair", "green_hair", "purple_hair",
        "orange_hair", "aqua_hair", "gradient_hair", "multicolored_hair",
        "long_hair", "short_hair", "medium_hair", "very_long_hair",
        "absurdly_long_hair", "ponytail", "twintails", "drill_hair",
        "sidelocks", "bun", "braid", "messy_hair", "straight_hair",
        "curly_hair", "wavy_hair", "bangs", "blunt_bangs", "parted_bangs",
        "sidelocked_bangs", "hair_over_one_eye", "hair_between_eyes",
        "ahoge", "streaked_hair", "highlighted_hair",
        # Headwear
        "cat_ears", "dog_ears", "fox_ears", "rabbit_ears", "wolf_ears",
        "bear_ears", "mouse_ears", "horse_ears", "deer_ears",
        "animal_ears", "ear_fluff", "tail",
        "cat_tail", "dog_tail", "fox_tail", "rabbit_tail",
        "horns", "wings", "halo", "antennae",
        "glasses", "sunglasses", "reading_glasses", "monocle",
        "hat", "beret", "fedora", "top_hat", "crown", "tiara",
        "headband", "hair_ribbon", "hair_tie", "hair_clip",
        "scarf", "choker", "necklace",
        # Clothing
        "shirt", "t-shirt", "blouse", "sweater", "hoodie", "jacket",
        "coat", "cape", "cloak", "suit", "blazer", "vest",
        "dress", "mini_dress", "maxi_dress", "sundress", "evening_gown",
        "school_uniform", "sailor_uniform", "military_uniform",
        "maid", "nurse", "teacher",
        "skirt", "mini_skirt", "maxi_skirt", "pleated_skirt",
        "shorts", "hot_pants", "jeans", "leggings", "tights",
        "pantyhose", "thighhighs", "kneehighs", "socks",
        "shoes", "boots", "heels", "sandals", "sneakers", "slippers",
        "gloves", "fingerless_gloves", "arm_guards",
        "bra", "underwear", "panties", "lingerie", "bikini",
        "swimsuit", "one-piece_swimsuit",
        "apron", "overalls", "jumpsuit", "bodysuit",
        "crop_top", "tube_top", "halterneck", "off-shoulder",
        "spaghetti_straps", "strapless",
        "zipped", "unzipped", "partially_unbuttoned",
        # Outfit styles
        "gothic", "lolita", "cyberpunk", "steampunk", "fantasy",
        "armor", "chainmail", "plate_armor", "leather",
        "latex", "pvc", "vinyl", "lace", "silk", "chiffon",
        "fur_trim", "feather_trim",
        # Accessories
        "earrings", "stud_earrings", "hoop_earrings", "dangle_earrings",
        "ring", "bracelet", "anklet", "brooch",
        "belt", "garter_belt", "suspenders",
        "weapon", "sword", "katana", "dagger", "gun", "rifle",
        "staff", "wand", "bow_(weapon)", "shield", "spear",
        "magic", "spell", "fire", "ice", "lightning", "water",
        "glowing", "sparkle", "particle_effects",
        # Pose
        "standing", "sitting", "lying", "kneeling", "crouching",
        "hands_on_hips", "arms_crossed", "arms_up", "hands_up",
        "waving", "pointing", "reaching", "holding",
        "spread_legs", "legs_together", "crossed_legs",
        "bent_over", "leaning_forward", "arched_back",
        "from_behind", "from_side", "from_front", "from_above",
        "from_below", "cowboy_shot", "portrait", "upper_body",
        "full_body", "close-up", "extreme_close-up",
        "top_down_view", "top_view", "side_view", "back_view",
        "dutch_angle", "tilted_frame",
        # Scene / environment
        "outdoors", "indoors", "bedroom", "bathroom", "kitchen",
        "classroom", "office", "library", "bathroom",
        "night", "day", "sunset", "sunrise", "dawn", "dusk",
        "cloudy", "rainy", "snowy", "sunny", "windy",
        "blue_sky", "stars", "moon", "rain", "fog",
        "forest", "mountain", "beach", "ocean", "river", "lake",
        "city", "street", "alley", "rooftop", "balcony",
        "castle", "dungeon", "cave", "ruins", "temple",
        "park", "garden", "field", "desert", "volcano",
        "underwater", "sky", "space", "tree", "flower",
        "cherry_blossoms", "autumn_leaves", "snow",
        "car", "motorcycle", "bicycle", "train", "airplane",
        "boat", "ship",
        # Quality
        "masterpiece", "best_quality", "highres", "absurdres",
        "ultra_detailed", "insanely_detailed", "realistic",
        "photorealistic", "8k", "4k", "hdr",
        "sharp_focus", "depth_of_field", "bokeh",
        "cinematic_lighting", "dramatic_lighting", "soft_lighting",
        "rim_lighting", "backlighting", "volumetric_lighting",
        "studio_lighting", "natural_lighting",
        "detailed_skin", "detailed_eyes", "detailed_face",
        "detailed_hair", "detailed_background",
        # Rating
        "rating:general", "rating:sensitive", "rating:questionable",
        "rating:explicit", "safe", "suggestive", "NSFW",
        # Actions
        "kissing", "hugging", "holding_hands", "embrace",
        "handjob", "footjob", "blowjob", "fellatio",
        "masturbation", "fingering", "cunnilingus",
        "sex", "missionary", "cowgirl", "doggy_style",
        "standing_sex", "sex_from_behind", "anal",
        "oral", "titjob", "cum", "cum_on_body",
        "cum_on_face", "cum_in_mouth", "cum_on_breasts",
        "cum_on_hair", "creampie",
        "paizuri", "foot_licking", "armpit_licking",
        "threesome", "foursome", "group",
        "bondage", "handcuffs", "chains", "rope",
        "blindfold", "gag", "collar",
        "spanking", "slapping", "hair_pull",
        "nipples", "erect_nipples", "puffy_nipples",
        "areolae", "nipple_piercing",
        "pussy", "pussy_juice", "wet_pussy",
        "clitoris", "labia", "vaginal",
        "penis", "erection", "big_penis",
        "testicles", "scrotum",
        "anus", "anal", "anal_fingering",
        "foot", "soles", "toes", "pedicure",
        "armpits", "armpit_hair",
        "cum_drip", "dildo", "vibrator", "sex_toy",
        "double_penetration", "triple_penetration",
        "gangbang", "creampie",
        # Emotions / states
        "ahegao", "ejaculation", "panting", "moaning",
        "drooling", "nosebleed", "heart",
        "sparkle", "glow", "aura",
        "chibi", "comic", "monochrome", "greyscale",
        "sketch", "lineart", "colored", "watercolor_(medium)",
        "oil_painting", "pixel_art", "3d", "render",
    ]:
        add(t, 0)

    # ── Specific tags (high post count) ─────────────────────────────────
    for t, c in [
        ("1girl", 500000), ("solo", 400000), ("masterpiece", 300000),
        ("best_quality", 280000), ("highres", 250000),
        ("absurdres", 200000), ("looking_at_viewer", 180000),
        ("long_hair", 170000), ("blonde_hair", 150000),
        ("blue_eyes", 140000), ("black_hair", 130000),
        ("smile", 120000), ("dress", 110000),
        ("white_background", 100000), ("simple_background", 95000),
        ("skirt", 90000), ("shirt", 85000),
        ("outdoors", 80000), ("breasts", 75000),
        ("large_breasts", 70000), ("brown_hair", 65000),
        ("open_mouth", 60000), ("blush", 55000),
        ("hands_on_hips", 50000), ("standing", 48000),
        ("cowboy_shot", 45000), ("upper_body", 42000),
        ("full_body", 40000), ("red_eyes", 38000),
        ("pink_hair", 36000), ("blue_hair", 34000),
        ("thighhighs", 32000), ("miniskirt", 30000),
        ("pleated_skirt", 28000), ("braid", 26000),
        ("ponytail", 25000), ("twintails", 24000),
        ("cat_ears", 23000), ("animal_ears", 22000),
        ("tail", 21000), ("horns", 20000),
        ("wings", 19000), ("halo", 18000),
        ("glasses", 17000), ("hat", 16000),
        ("cape", 15000), ("armor", 14000),
        ("sword", 13000), ("weapon", 12000),
        ("night", 11000), ("day", 10000),
        ("sunset", 9500), ("rain", 9000),
        ("snow", 8500), ("flower", 8000),
        ("tree", 7500), ("ocean", 7000),
        ("mountain", 6500), ("forest", 6000),
        ("city", 5500), ("castle", 5000),
        ("bedroom", 4500), ("bathroom", 4000),
        ("kitchen", 3800), ("classroom", 3600),
        ("library", 3400), ("office", 3200),
        ("from_above", 3000), ("from_side", 2800),
        ("from_behind", 2600), ("from_below", 2400),
        ("dutch_angle", 2200), ("tilted_frame", 2000),
        ("close-up", 1800), ("extreme_close-up", 1600),
        ("portrait", 1500), ("photorealistic", 1400),
        ("realistic", 1300), ("ultra_detailed", 1200),
        ("cinematic_lighting", 1100), ("dramatic_lighting", 1000),
        ("soft_lighting", 900), ("rim_lighting", 800),
        ("backlighting", 700), ("volumetric_lighting", 600),
        ("depth_of_field", 500), ("bokeh", 400),
        ("nude", 30000), ("naked", 28000),
        ("pussy", 25000), ("pussy_juice", 20000),
        ("spread_legs", 15000), ("legs_apart", 12000),
        ("on_back", 10000), ("missionary", 8000),
        ("cowgirl_position", 7000), ("doggy_style", 6000),
        ("standing_sex", 5000), ("sex_from_behind", 4000),
        ("cum_on_body", 3500), ("cum_on_face", 3000),
        ("cum_in_mouth", 2800), ("cum_on_breasts", 2600),
        ("cum_on_hair", 2400), ("cum", 2200),
        ("creampie", 2000), ("paizuri", 1800),
        ("blowjob", 1600), ("fellatio", 1400),
        ("handjob", 1200), ("footjob", 1000),
        ("masturbation", 900), ("fingering", 800),
        ("cunnilingus", 700), ("oral", 600),
        ("titjob", 500), ("anal", 400),
        ("bondage", 3000), ("rope", 2500),
        ("handcuffs", 2000), ("blindfold", 1800),
        ("collar", 1600), ("gag", 1400),
        ("nipples", 20000), ("erect_nipples", 15000),
        ("areolae", 10000), ("nipple_piercing", 5000),
        ("anus", 8000), ("clitoris", 6000),
        ("labia", 4000), ("penis", 10000),
        ("erection", 8000), ("big_penis", 5000),
        ("testicles", 6000), ("foot", 3000),
        ("soles", 2000), ("toes", 1500),
        ("armpits", 1000), ("armpit_hair", 500),
        ("dildo", 2000), ("vibrator", 1500),
        ("sex_toy", 1000),
        ("double_penetration", 1500), ("triple_penetration", 800),
        ("gangbang", 2000), ("group", 3000),
        ("threesome", 2500), ("foursome", 1000),
        ("kissing", 4000), ("hugging", 3000),
        ("holding_hands", 2000), ("embrace", 1500),
        ("ahegao", 3000), ("ejaculation", 2000),
        ("panting", 1500), ("moaning", 1000),
        ("drooling", 800), ("nosebleed", 500),
        ("heart", 2000), ("sparkle", 1500),
        ("glow", 1000), ("aura", 800),
        ("rating:general", 500000), ("rating:sensitive", 200000),
        ("rating:questionable", 150000), ("rating:explicit", 100000),
        ("safe", 400000), ("suggestive", 180000), ("NSFW", 120000),
        ("lowres", 50000), ("bad_anatomy", 40000),
        ("bad_hands", 30000), ("text", 25000),
        ("error", 20000), ("missing_fingers", 18000),
        ("extra_digit", 15000), ("fewer_digits", 12000),
        ("cropped", 10000), ("worst_quality", 45000),
        ("low_quality", 40000), ("normal_quality", 35000),
        ("jpeg_artifacts", 25000), ("signature", 20000),
        ("watermark", 18000), ("username", 15000),
        ("blurry", 30000),
    ]:
        add(t, 0, c)

    # ── Artist tags (category 1) ────────────────────────────────────────
    artists = [
        "wlop", "miwa_shirow", "hews_ac", "fafanon", "ilya_kuvshinov",
        "miikareijin", "konomi_yuuki", "lack", "redjuice", "acky Bright",
        "pako (sousou no frieren)", "kentaro_miura", "yoshitaka_amano",
        "hajime_sorayama", "tsutomu_nihei", "range_murata",
        "yusuke_kozaki", "shigenori_sojima", "kazuma_kaneko",
        "akira_toriyama", "masamune_shirow", "katsuhiro_otomo",
        "hayao_miyazaki", "hideaki_anno", "yoh_yoshinari",
        "hiroyuki_imaishi", "kazuki_takahashi", "takehito_harada",
        "tite_kubo", "eiichiro_oda", "akira_toriyama",
        "yusuke_murata", "one (artist)", "minguk_kang",
        "greg_rutkowski", "artgerm", "rossdraws", "wlop",
        "guweiz", "alphonse_mucha", "gustav_klimt",
        "hokusai", "ukiyo-e",
    ]
    for a in artists:
        add(a.lower(), 1, 500)

    # ── Copyright tags (category 3) ─────────────────────────────────────
    copyrights = [
        "genshin_impact", "honkai_impact_3rd", "honkai_star_rail",
        "fate/grand_order", "fate/stay_night", "fate/zero",
        "fate/hollow_ataraxia", "fate/apocrypha", "fate/extra",
        "fate/caliburn", "fate/grand_order_babylonia",
        "the_elder_scrolls", "skyrim", "fallout",
        "witcher", "cyberpunk_2077", "mass_effect",
        "dragon_age", "dark_souls", "bloodborne", "elden_ring",
        "monster_hunter", "resident_evil", "final_fantasy",
        "final_fantasy_vii", "final_fantasy_xiv",
        "nier_automata", "nier_replicant", "nier",
        "persona_5", "persona_4", "persona_3",
        "kingdom_hearts", "kingdom_hearts_iii",
        "the_legend_of_zelda", "breath_of_the_wild", "tears_of_the_kingdom",
        "super_mario", "pokemon", "pokémon",
        "animal_crossing", "splatoon", "metroid",
        "sonic_the_hedgehog", "mega_man",
        "metal_gear", "metal_gear_solid",
        "silent_hill", "castlevania", "contra",
        "street_fighter", "tekken", "mortal_kombat",
        "super_smash_bros", "tekken",
        "demon_slayer", "kimetsu_no_yaiba",
        "jujutsu_kaisen", "my_hero_academia",
        "attack_on_titan", "shingeki_no_kyojin",
        "one_punch_man", "one_piece", "naruto",
        "bleach", "dragon_ball", "dragon_ball_z",
        "sword_art_online", "that_time_i_got_reincarnated_as_a_slime",
        "re:zero", "konosuba", "mushoku_tensei",
        "overlord", "no_game_no_life",
        "evangelion", "neon_genesis_evangelion",
        "ghost_in_the_shell", "akira",
        "cowboy_bebop", "trigun", "berserk",
        "fullmetal_alchemist", "hunter_x_hunter",
        "death_note", "code_geass", "steins;gate",
        "clannad", "angel_beats", "toradora!",
        "the_devil_is_a_part_timer", "kono_suba",
        "reincarnated_as_a_slime", "shield_hero",
        "solo_leveling", "tower_of_god",
        "the_mushroom_tamarin", "blue_lock",
        "spy_x_family", "chainsaw_man", "frieren",
        "oshi_no_ko", "bocchi_the_rock!",
        "lycoris_recoil", "violet_evergarden",
        "karakai_jouzu_no_takagi-san",
        "horimiya", "rent-a-girlfriend",
        "quintessential_quintuplets",
        "love_is_war", "kaguya-sama",
        "toradora", "clannad",
        "sword_art_online", "log_horizon",
        "grimgar", "overlord",
        "the_rising_of_the_shield_hero",
        "goblin_slayer", "konosuba",
        "re:zero", "no_game_no_life",
    ]
    for c in copyrights:
        add(c.lower(), 3, 1000)

    # ── Character tags (category 4) ─────────────────────────────────────
    characters = [
        # Genshin Impact
        "lumine_(genshin_impact)", "aether_(genshin_impact)",
        "raiden_shogun", "yae_miko", "hu_tao", "ganyu",
        "zhongli", "kazuha", "arataki_itto", "ayaka",
        "fischl_(genshin_impact)", "venti_(genshin_impact)",
        "jean_(genshin_impact)", "diluc_(genshin_impact)",
        "keqing_(genshin_impact)", "qiqi_(genshin_impact)",
        "ningguang_(genshin_impact)", "beidou_(genshin_impact)",
        # Honkai
        "kiana_kaslana", "mei_(honkai_impact_3rd)",
        "bronya_zaychik", "theresa_(honkai_impact_3rd)",
        "Seele_Vollerei", "fuhua_(honkai_impact_3rd)",
        "kafka_(honkai_star_rail)", "ilvermorny",
        "herta_(honkai_star_rail)", "astafan",
        "firefly_(honkai_star_rail)",
        # Fate
        "saber_(fate)", "artoria_pendragon",
        "rin_tohsaka", "sakura_matou", "iliasviel_von_einzbern",
        "archer_(fate)", "lancer_(fate)", "rider_(fate)",
        "caster_(fate)", "assassin_(fate)", "berserker_(fate)",
        "gilgamesh_(fate)", "shirou_emiya",
        "emiya_shirou", "avenger_(fate)",
        # Evangelion
        "asuka_langley_soryu", "rei_ayanami",
        "misato_katsuragi", "rei_ayanami_(sourced)",
        "mari_makinami_illustrious",
        # SAO
        "asuna_(sword_art_online)", "kirito_(sword_art_online)",
        "leafa_(sword_art_online)", "sinon_(sword_art_online)",
        "alice_(sword_art_online)",
        # Dragon Ball
        "goku", "vegeta", "gohan", "trunks_(dragon_ball)",
        "bulma", "chi-chi", "android_18",
        "frieza", "cell_(dragon_ball)", "majin_buu",
        # Naruto
        "naruto_uzumaki", "sasuke_uchiha", "sakura_haruno",
        "kakashi_hatake", "hinata_hyuga", "itachi_uchiha",
        "madara_uchiha", "obito_uchiha", "gaara",
        # One Piece
        "monkey_d._luffy", "roronoa_zoro", "nami_(one_piece)",
        "usopp", "sanji", "tony_tony_chopper",
        "robin_(one_piece)", "franky", "brook",
        # Bleach
        "ichigo_kurosaki", "rukia_kuchiki",
        " Orihime_Inoue", "renji_abarai",
        "byakuya_kuchiki", "toshiro_hitsugaya",
        # Jujutsu Kaisen
        "yuuji_itadori", "megumi_fushiguro",
        "nobara_kugisaki", "satoru_gojo",
        "ryomen_sukuna", "todo_akihiro",
        # Demon Slayer
        "tanjiro_kamado", "nezuko_kamado",
        "zenitsu_agatsuma", "inosuke_hashibira",
        "shinobu_kochou", "mitsuri_kanroji",
        "muichiro_tokito", "gyomei_himejima",
        # My Hero Academia
        "izuku_midoriya", "katsuki_bakugou",
        "shoto_todoroki", "ochaco_uraraka",
        "tenya_iida", "dabi_(my_hero_academia)",
        "tomura_shigaraki", "all_might",
        # Spy x Family
        "anya_forger", "loid_forger", "yor_forger",
        # Chainsaw Man
        "denji_(chainsaw_man)", "makima_(chainsaw_man)",
        "power_(chainsaw_man)", "aki_hayakawa",
        # Frieren
        "frieren", "stark_(frieren)", "fern_(frieren)",
        # Attack on Titan
        "eren_yeager", "mikasa_ackerman",
        "armin_arlert", "levi_ackerman",
        # One Punch Man
        "saitama", "genos", "tatsumaki",
        # Evangelion
        "asuka_langley_soryu", "rei_ayanami",
        # Classic
        "hatsune_miku", "kagamine_rin", "kagamine_len",
        "megurine_luka", "kaito_(vocaloid)", "meiko_(vocaloid)",
        "gumi_(vocaloid)", "ia_(vocaloid)",
        # Nier
        "2b_(nier:automata)", "9s_(nier:automata)",
        "a2_(nier:automata)", "emil_(nier)",
        # Persona
        "joker_(persona_5)", "ryuji_sakamoto",
        "ann_takamaki", "yusuke_kitagawa",
        "makoto_niijima", "futaba_sakura",
        "haru_okumura", "goro_akechi",
        # Touhou
        "reimu_hakurei", "marisa_kirisame",
        "sakuya_izayoi", "remilia_scarlet",
        "flandre_scarlet", "cirno",
        "youmu_konpaku", "yukari_yakumo",
        "suika_ibuki", "ran_yakumo",
        # Fire Emblem
        "marth_(fire_emblem)", "ike_(fire_emblem)",
        "lucina_(fire_emblem)", "chrom_(fire_emblem)",
        "lysaithra", "edelgard",
        # Xenoblade
        "shulk", "pyra_(xenoblade)", "mythra_(xenoblade)",
        "noah_(xenoblade_3)", "mio_(xenoblade_3)",
        # Zelda
        "link", "zelda_(legend_of_zelda)",
        "ganon", "midna", "imp_(zelda)",
        # Mario
        "mario_(character)", "princess_peach",
        "luigi", "princess_daisy", "rosalina",
        # Pokemon
        "red_(pokemon)", "leaf_(pokemon)",
        "n_(pokemon)", "cynthia_(pokemon)",
        "lance_(pokemon)", "steven_stone",
        # FNAF
        "fnaf", "animatronic",
        # Miscellaneous
        "2b_(nier)", "a2_(nier)",
        "bayonetta_(character)", "jill_valentine",
        "tifa_lockhart", "aerith_gainsborough",
        "lightning_(final_fantasy)", "yuna_(final_fantasy)",
        "tifa_lockhart", "rinoa_heartilly",
        "princess_zelda", "zelda_(spirit_tracks)",
        "link_(breath_of_the_wild)", "link_(twilight_princess)",
        "cloud_strife", "sephiroth", "zack_fair",
        "vincent_valentine", "red_xiii",
        "tidus", "wakka", "auron",
        "vaan", "basch", "balthier",
        "noctis_lucis_caelum", "prompto_argentum",
        "gladiolus_amicitia", "ignis Scientia",
        "arsyn", "tidus",
    ]
    for c in characters:
        add(c.lower(), 4, 800)

    # ── Meta tags (category 5) ──────────────────────────────────────────
    meta_tags = [
        "lowres", "bad_anatomy", "bad_hands", "text", "error",
        "missing_fingers", "extra_digit", "fewer_digits", "cropped",
        "worst_quality", "low_quality", "normal_quality", "jpeg_artifacts",
        "signature", "watermark", "username", "blurry",
        "artist_name", "Artist:ERROR", "commentary",
        "comic", "monochrome", "greyscale", "grayscale",
        "sketch", "lineart", "line_art",
        "colored", "watercolor_(medium)", "oil_painting",
        "pixel_art", "3d", "render",
        "chibi", "super_deformed", "highres",
        "absurdres", "insanely_detailed",
        "multiple_views", "sheet_(turnaround)",
        "concept_art", "promotional_material",
        "game_cg", "anime_screenshot", "manga_scan",
        "web_manga", "webtoon", "visual_novel",
        "doujinshi", "official",
    ]
    for t in meta_tags:
        add(t.lower(), 5, 500)

    # ── Expanded comprehensive tags ─────────────────────────────────────
    # Additional general tags for better coverage
    expanded = [
        # More body variants
        "huge_breasts", "very_large_breasts", "modest_breasts",
        "bouncy_breasts", "sagging_breasts", "upturned_breasts",
        "wide_hips", "narrow_waist", "hourglass_figure",
        "thick_eyebrows", "thin_eyebrows", "eyebrows_through_hair",
        "pointy_ears", "elf_ears", "demonic_ears",
        "dark_skin", "very_dark_skin", "light_skin", "medium_skin",
        "white_skin", "olive_skin", "bronze_skin",
        # More hair styles
        "dreadlocks", "afro", "mohawk", "undercut", "bob_cut",
        "pixie_cut", "bowl_cut", "buzz_cut", "crew_cut",
        "hair_over_both_eyes", "single_braid", "twin_braids",
        "side_braid", "low_twinlongtails", "drill_twintails",
        "hair_up", "half_updo", "hime_cut", "odango",
        "side ponytail", "wavy_long_hair", "spiked_hair",
        # More emotions
        "tsundere", "yandere", "kuudere", "dandere",
        "crying", "sobbing", "tears_of_joy",
        "scared", "terrified", "shocked", "surprised",
        "confused", "dizzy", "sleepy", "bored",
        "excited", "happy", "sad", "angry",
        "determined", "serious", "smug", "arrogant",
        "embarrassed", "flustered", "mortified",
        "seductive_pose", "seductive_smile", "beckoning",
        # More poses
        "arms_at_sides", "arms_behind_back", "hand_on_own_hip",
        "hand_on_own_cheek", "hand_on_own_face", "hand_on_own_head",
        "hand_in_pocket", "finger_to_mouth", "finger_gun",
        "peace_sign", "v-sign", "thumbs_up", "waving_hand",
        "salute", "praying", "crossed_arms", "arms_up",
        "leaning_back", "leaning_forward", "slouching",
        "on_all_fours", "squatting", "kneeling", "prostrate",
        "back_bend", "bridge_pose", "headstand",
        "lying_on_back", "lying_on_side", "lying_on_stomach",
        "floating", "flying", "jumping", "running", "walking",
        "turning_around", "looking_back", "over_the_shoulder",
        # More outfit details
        "detached_sleeves", "off_shoulder", "one_rshoulder",
        "asymmetrical_clothing", "layered_clothing", "torn_clothes",
        "wet_clothes", "see-through", "translucent_clothing",
        "open_jacket", "unbuttoned_shirt", "partially_undressed",
        "shirt_lift", "skirt_lift", "panties_pull",
        "garter", "garter_belt", "stockings", "thigh_highs",
        "knee_highs", "ankle_socks", "toeless_pantyhose",
        "high_waist", "low_rise", "bare_shoulders",
        # More accessories
        "hairpin", "hair_ornament", "flower_(hairpin)",
        "hair_scrunchie", "headpiece", "crown",
        "tiara", "diadem", "circlet",
        "pendant", "choker", "collar", "necklace",
        "locket", "amulet", "talisman",
        "wrist_cuffs", "armband", "armlet",
        "anklet", "toe_ring", "body_chain",
        "body_piercing", "belly_button_piercing", "tongue_piercing",
        "lip_piercing", "nose_piercing", "eyebrow_piercing",
        # More scene elements
        "campfire", "bonfire", "fireplace", "candles",
        "lantern", "chandelier", "neon_signs",
        "window", "door", "staircase", "balcony",
        "mirror", "painting", "bookshelf", "desk",
        "bed", "sofa", "chair", "table",
        "bathtub", "shower", "pool", "hot_spring",
        "jacuzzi", "fountain", "well",
        "bridge", "gate", "fence", "wall",
        "roof", "ceiling", "floor", "carpet",
        "blanket", "pillow", "curtain",
        "shadow", "light_rays", "lens_flare",
        "bokeh", "motion_blur", "speed_lines",
        "impact_frames", "chromatic_aberration",
        # More nature
        "butterfly", "butterflies", "bird", "birds",
        "cat", "dog", "rabbit", "horse", "deer",
        "fox", "wolf", "bear", "lion", "tiger",
        "elephant", "giraffe", "panda", "penguin",
        "dolphin", "whale", "shark", "octopus",
        "fish", "snake", "lizard", "turtle",
        "frog", "spider", "bee", "ant",
        "ladybug", "dragonfly", "snail",
        "mushroom", "moss", "ivy", "vine",
        "leaf", "leaves", "petal", "petals",
        "bamboo", "cactus", "succulent",
        "rose", "lily", "lotus", "sunflower",
        "cherry_blossom", "maple_leaf", "clover",
        "four_leaf_clover", "crystal", "gem",
        "jewel", "diamond", "ruby", "sapphire", "emerald",
        "gold", "silver", "platinum", "copper",
        # More abstract / effect tags
        "light", "darkness", "shadow", "silhouette",
        "glow", "sparkle", "shimmer", "shine",
        "reflection", "refraction", "prism",
        "rainbow", "aurora", "nebula", "galaxy",
        "constellation", "star", "stars", "moon",
        "sun", "sunset_sunrise", "cloud",
        "fog", "mist", "haze", "smoke",
        "steam", "dust", "particles",
        "flame", "fire", "inferno", "blaze",
        "water", "rain", "puddle", "wave", "waves",
        "ice", "snow", "frost", "icicle",
        "lightning", "thunder", "storm",
        "wind", "tornado", "hurricane",
        "earthquake", "eruption", "magma", "lava",
        "sand", "dust_storm", "mirage",
        # More quality / style tags
        "high_detail", "ultra_realistic", "hyperrealistic",
        "photorealistic_render", "cgi", "3d_render",
        "unreal_engine", "octane_render", "vray",
        "ray_tracing", "global_illumination",
        "subsurface_scattering", "ambient_occlusion",
        "film_grain", "lens_flare", "chromatic_aberration",
        "vignette", "bloom", "hdr", "tone_mapping",
        "color_grading", "color_correction",
        "black_and_white", "sepia", "duotone",
        "cel_shading", "toon_shading", "flat_shading",
        "cross_hatching", "stippling", "pointillism",
        "watercolor", "oil_painting", "acrylic",
        "pencil_(medium)", "charcoal", "ink",
        "digital_painting", "vector", "pixel_art",
        "8-bit", "16-bit", "retro", "vintage",
        "glitch_art", "vaporwave", "synthwave",
        "noir", "film_noir", "chiaroscuro",
        # More NSFW / adult tags
        "spread_pussy", "spread_eagle", "leg_up",
        "feet_up", "ass_up", "face_sitting",
        "sixty_nine", "foot_fetish", "ass_fetish",
        "breast_fetish", "thigh_fetish", "armpit_fetish",
        "stocking_fetish", "uniform_fetish", "maid_fetish",
        "nurse_fetish", "school_girl",
        "ahegao", "ejaculation", "multiple_cream",
        "cum_on_body", "cum_drip", "cum_pool",
        "cum_still_dripping", "cum_overflow",
        "tongue_out", "licking", "biting_lip",
        "sweat_on_body", "saliva", "drool",
        "nosebleed", "blushing_heavily",
        "post-orgasm", "pre-orgasm",
        "panties_down", "bra_off", "shirt_lift",
        "ass_grab", "breast_grab", "nipple_rub",
        "clitoral_rub", "penis_rub",
        "fellatio", "deepthroat", "cum_on_tongue",
        "cum_in_mouth", "swallowing",
        "titjob", "paizuri", "between_breasts",
        "footjob", "toejob", "sole_job",
        "handjob", " handjob", "male handjob",
        "cunnilingus", "rimming", "anilingus",
        "fingering", "masturbation", "dildo",
        "vibrator", "anal_beads", "plug_(sex)",
        "chastity_cage", "chastity_belt",
        "nipple_clamps", "clit_clamp",
        "whip", "paddle", "crop",
        "bondage", "rope_bondage", "shibari",
        "handcuffs", "chains", "restraints",
        "blindfold", "gag", "ball_gag",
        "collar", "leash", "pet_play",
        "stockings", "thighhighs", "pantyhose",
        "garter_belt", "suspenders",
        "high_heels", "stiletto",
        "lingerie", "babydoll", "chemise",
        "corset", "bustier", "body_stocking",
        "babydoll_(clothing)", "slip_(clothing)",
        "nightgown", "negligee",
        "playboy", "hustler", "penthouse",
        "onlyfans", "fansly", "patreon",
        "masturbation", "masturbating",
        "fingering_self", " rubbing_clitoris",
        "dildo_riding", "vibrator_on_clitoris",
        "anal_plug", "butt_plug",
        "anal_fisting", "fisting",
        "double_penetration", "triple_penetration",
        "quad_penetration", "gangbang",
        "creampie", "internal_cumshot",
        "ejaculation", "cum_on_face",
        "cum_on_breasts", "cum_on_ass",
        "cum_on_hair", "cum_drip",
        "cum_in_pussy", "cum_in_ass",
        "cum_in_mouth", "cum_swallowing",
        "multiple_cumshots", "cum_trophy",
        "cum_covered", "cum_everywhere",
        "queening", "facesitting",
        "smothering", "ass_smothering",
        "foot_smothering", "breast_smothering",
        "trampling", "crushing",
        "spitting", "drooling",
        "urination", "enema",
        "scat", "vore",
        "macrophilia", "microphilia",
        "vore", "vore_guro",
        "guro", "gore", "torture",
        "amputation", "disembowelment",
        "vore", "vore_vore",
        "vore_guro", "vorevore",
    ]
    for t in expanded:
        add(t.strip().lower(), 0, 200)

    # ── Missing commonly-used Danbooru tags ─────────────────────────────
    # Added to fix false invalid flags from user testing
    missing_tags = [
        # Actor counts
        "1girl", "2girls", "3girls", "4girls", "5girls", "6+girls",
        "1boy", "2boys", "3boys", "4boys", "5boys", "6+boys",
        "1other", "2others", "3others",
        "multiple_girls", "multiple_boys", "multiple_other",
        "no_humans",
        # Sexual / action tags
        "hetero", "homo", "yaoi", "yuri", "futanari", "intercourse",
        "sex", "masturbation", "oral", "anal", "vaginal",
        "masturbation", "fingering", "cunnilingus", "fellatio",
        "handjob", "footjob", "titjob", "paizuri",
        "blowjob", "deepthroat", "rimjob",
        "cum", "cumshot", "creampie", "cum_in_mouth",
        "cum_on_body", "cum_on_face", "cum_on_breasts",
        "cum_on_hair", "cum_in_pussy", "cum_in_ass",
        "ejaculation", "multiple_cumshots", "cum_trophy",
        "cum_drip", "cum_pool", "cum_covered",
        "pussy_juice", "wet_pussy", "spread_pussy",
        "nipples", "erect_nipples", "puffy_nipples", "nipples_visible",
        "pussy", "clitoris", "labia", "anus", "anus_visible",
        "penis", "erection", "big_penis", "small_penis",
        "testicles", "scrotum",
        "navel", "belly_button",
        "foot", "sole", "soles", "toes", "toeless_pantyhose",
        "armpits", "armpit_hair",
        "threesome", "foursome", "fivesome", "group",
        "gangbang", "double_penetration", "triple_penetration",
        "dp", "tp",
        "missionary", "cowgirl", "reverse_cowgirl",
        "doggy_style", "standing_sex", "sex_from_behind",
        "on_top", "on_back", "on_side",
        "legs_up", "legs_spread", "spread_legs", "legs_together",
        "feet_up", "ass_up", "face_sitting",
        "sixty_nine", "69",
        "kissing", "french_kiss", "tongue_kiss",
        "hugging", "holding_hands", "embrace",
        "grope", "breast_grab", "ass_grab", "crotch_grab",
        "sex_toy", "dildo", "vibrator", "anal_plug", "butt_plug",
        "chastity_cage", "chastity_belt",
        "nipple_clamps", "clit_clamp",
        "whip", "paddle", "crop", "spanking",
        "bondage", "rope_bondage", "shibari",
        "handcuffs", "chains", "restraints",
        "blindfold", "gag", "ball_gag",
        "collar", "leash", "pet_play",
        # Pose tags
        "standing", "sitting", "lying", "kneeling", "crouching",
        "on_all_fours", "squatting", "leaning_forward", "leaning_back",
        "arched_back", "back_bend", "bridge_pose",
        "hands_on_hips", "arms_crossed", "arms_up", "hands_up",
        "waving", "pointing", "peace_sign", "v-sign",
        "finger_to_mouth", "finger_gun", "thumbs_up",
        "praying", "salute", "beckoning",
        "looking_at_viewer", "looking_away", "looking_up",
        "looking_down", "looking_back", "side-eye",
        "from_above", "from_below", "from_side", "from_behind",
        "from_front", "cowboy_shot", "portrait", "upper_body",
        "full_body", "close-up", "extreme_close-up",
        "top_down_view", "top_view", "side_view", "back_view",
        "dutch_angle", "tilted_frame",
        # Skin / body variants
        "dark_skin", "very_dark_skin", "light_skin", "medium_skin",
        "pale_skin", "tan", "tanned", "olive_skin", "bronze_skin",
        "glossy_skin", "shiny_skin", "wet_skin", "oily_skin",
        "detailed_skin", "smooth_skin", "rough_skin",
        "freckles", "moles", "birthmark", "scar",
        "muscles", "abs", "six-pack", "toned",
        "broad_shoulders", "narrow_waist", "wide_hips",
        "thick_thighs", "slim_thighs", "long_legs",
        "petite", "curvy", "voluptuous", "athletic",
        # Hair variants
        "blonde_hair", "black_hair", "brown_hair", "red_hair",
        "blue_hair", "pink_hair", "white_hair", "grey_hair",
        "green_hair", "purple_hair", "orange_hair", "aqua_hair",
        "gradient_hair", "multicolored_hair", "streaked_hair",
        "highlighted_hair", "two-tone_hair",
        "long_hair", "short_hair", "medium_hair", "very_long_hair",
        "absurdly_long_hair", "floor_length_hair",
        "ponytail", "high_ponytail", "low_ponytail", "side_ponytail",
        "twintails", "drill_hair", "drill_twintails",
        "sidelocks", "bun", "double_bun", "odango",
        "messy_hair", "wet_hair", "windblown_hair",
        "straight_hair", "curly_hair", "wavy_hair",
        "bangs", "blunt_bangs", "side_swept_bangs",
        "parted_bangs", "hair_over_eye", "hair_over_both_eyes",
        "ahoge", "single_ahoge",
        "braid", "single_braid", "twin_braids", "side_braid",
        "dreadlocks", "afro", "mohawk", "undercut",
        "bob_cut", "pixie_cut", "hime_cut",
        "hair_up", "half_updo", "hair_down",
        "hair_ornament", "hair_ribbon", "hair_clip", "hair_tie",
        "hairpin", "flower_(hairpin)", "scrunchie",
        # Eye variants
        "blue_eyes", "green_eyes", "red_eyes", "brown_eyes",
        "golden_eyes", "purple_eyes", "grey_eyes", "black_eyes",
        "heterochromia", "slit_pupils", "vertical_pupils",
        "long_eyelashes", "thick_eyelashes",
        "closed_eyes", "half-closed_eyes", "one_eye_closed",
        "wink", "cross-eyed", "lazy_eye",
        # Face / emotion
        "smile", "grin", "smirk", "frown", "pout",
        "open_mouth", "closed_mouth", "mouth_hold",
        "blush", "light_blush", "heavy_blush",
        "sweat", "sweatdrop", "tears", "tears_of_joy",
        "angry", "embarrassed", "shy", "flustered",
        "seductive", "seductive_smile", "seductive_pose",
        "ahegao", "tongue_out", "biting_lip",
        "panting", "moaning", "drooling", "nosebleed",
        "heart", "sparkles", "glow", "aura",
        # Headwear / accessories
        "cat_ears", "dog_ears", "fox_ears", "rabbit_ears",
        "wolf_ears", "bear_ears", "mouse_ears", "horse_ears",
        "animal_ears", "ear_fluff",
        "cat_tail", "dog_tail", "fox_tail", "rabbit_tail",
        "tail", "horns", "demon_horns", "dragon_horns",
        "wings", "angel_wings", "demon_wings", "bat_wings",
        "halo", "angel_halo",
        "glasses", "sunglasses", "reading_glasses", "monocle",
        "hat", "beret", "fedora", "top_hat", "crown", "tiara",
        "headband", "headpiece", "circlet",
        "choker", "collar", "necklace", "pendant",
        "earrings", "hoop_earrings", "stud_earrings",
        "ring", "bracelet", "anklet", "brooch",
        "belt", "garter_belt", "suspenders",
        # Clothing
        "shirt", "t-shirt", "blouse", "sweater", "hoodie",
        "jacket", "coat", "cape", "cloak",
        "suit", "blazer", "vest", "cardigan",
        "dress", "mini_dress", "maxi_dress", "sundress",
        "evening_gown", "cocktail_dress",
        "school_uniform", "sailor_uniform", "military_uniform",
        "maid", "nurse", "teacher", "secretary",
        "skirt", "mini_skirt", "maxi_skirt", "pleated_skirt",
        "shorts", "hot_pants", "jeans", "leggings",
        "pantyhose", "thighhighs", "kneehighs", "socks",
        "shoes", "boots", "heels", "stiletto",
        "sandals", "sneakers", "slippers",
        "gloves", "fingerless_gloves",
        "bra", "underwear", "panties", "lingerie",
        "bikini", "swimsuit", "one-piece_swimsuit",
        "apron", "overalls", "jumpsuit", "bodysuit",
        "crop_top", "tube_top", "halterneck",
        "off_shoulder", "off-shoulder", "one_rshoulder",
        "spaghetti_straps", "strapless",
        "detached_sleeves", "bare_shoulders",
        "open_jacket", "unbuttoned", "partially_undressed",
        "torn_clothes", "wet_clothes", "see-through",
        "translucent_clothing", "sheer_clothing",
        "lace", "silk", "chiffon", "leather", "latex",
        "fur_trim", "feather_trim",
        "corset", "bustier", "body_stocking",
        "babydoll", "chemise", "negligee", "nightgown",
        "slip_(clothing)",
        # Quality / style
        "masterpiece", "best_quality", "highres", "absurdres",
        "ultra_detailed", "insanely_detailed",
        "realistic", "photorealistic", "hyperrealistic",
        "8k", "4k", "hdr",
        "sharp_focus", "depth_of_field", "bokeh",
        "cinematic_lighting", "dramatic_lighting",
        "soft_lighting", "rim_lighting", "backlighting",
        "volumetric_lighting", "studio_lighting",
        "natural_lighting", "golden_hour",
        "detailed_eyes", "detailed_face", "detailed_hair",
        "detailed_background", "detailed_skin",
        "realistic_anatomy", "good_anatomy",
        "good_hands", "detailed_hands",
        # Rating
        "rating:general", "rating:sensitive",
        "rating:questionable", "rating:explicit",
        "safe", "suggestive", "nsfw",
        # Meta / quality downvotes
        "lowres", "bad_anatomy", "bad_hands", "bad_proportions",
        "text", "error", "missing_fingers", "extra_digit",
        "fewer_digits", "cropped", "worst_quality",
        "low_quality", "normal_quality", "jpeg_artifacts",
        "signature", "watermark", "username", "blurry",
        "disfigured", "deformed", "mutated",
        # Scene / location
        "outdoors", "indoors", "bedroom", "bathroom",
        "kitchen", "classroom", "office", "library",
        "night", "day", "sunset", "sunrise", "dawn",
        "cloudy", "rainy", "snowy", "sunny",
        "blue_sky", "stars", "moon", "rain", "fog",
        "forest", "mountain", "beach", "ocean", "river",
        "city", "street", "alley", "rooftop",
        "castle", "dungeon", "cave", "ruins",
        "park", "garden", "field", "desert",
        "underwater", "sky", "space",
        "tree", "flower", "cherry_blossoms",
        "campfire", "fireplace", "candles",
        "mirror", "window", "door",
        "bed", "sofa", "chair", "table",
        "bathtub", "shower", "pool", "hot_spring",
        "car", "motorcycle", "bicycle",
        # NSFW body parts (comprehensive)
        "spread_pussy", "spread_eagle",
        "ass", "big_ass", "small_ass",
        "breasts", "big_breasts", "small_breasts",
        "medium_breasts", "huge_breasts", "flat_chest",
        "cleavage", "underboob", "sideboob",
        "areolae", "nipple_piercing",
        "midriff", "navel", "collarbone",
        "thighs", "thick_thighs", "inner_thigh",
        "ankles", "wrists", "neck",
        "face", "lips", "tongue", "teeth",
        "tongue_out", "licking",
        # BDSM / fetish
        "bondage", "rope", "shibari",
        "handcuffs", "chains", "restraints",
        "blindfold", "gag", "ball_gag",
        "collar", "leash",
        "stockings", "thighhighs", "pantyhose",
        "garter_belt", "suspenders",
        "high_heels", "stiletto",
        "lingerie", "babydoll", "chemise",
        "corset", "bustier", "body_stocking",
    ]
    for t in missing_tags:
        add(t.strip().lower(), 0, 500)

    return tags


def main():
    tags = build_database()

    output = {
        "_meta": {
            "total_tags": len(tags),
            "generated_at": __import__("time").strftime("%Y-%m-%d %H:%M:%S"),
            "mode": "builtin",
            "categories": {0: "general", 1: "artist", 3: "copyright", 4: "character", 5: "meta"},
        },
        "tags": tags,
    }

    with OUTPUT.open("w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False)

    size_mb = OUTPUT.stat().st_size / 1024 / 1024
    print(f"Generated {len(tags)} tags → {OUTPUT} ({size_mb:.1f} MB)")


if __name__ == "__main__":
    main()
